### ISSUE TITLE
Cannot build NSIS via Electron-Builder inside Docker on Apple Silicon host

### ISSUE THREAD

**Issue by Nantris** [develar/app-builder#100] opened 2024-02-08 23:18 UTC
Using this package via `electron-builder` inside a Docker on an Apple M2 machine results in:

```
⨯ cannot execute  cause=signal: segmentation fault
                    errorOut=qemu: uncaught target signal 11 (Segmentation fault) - core dumped

                    command=wine /root/.cache/electron-builder/winCodeSign/winCodeSign-2.6.0/rcedit-ia32.exe '/tmp/et-db411cd21f3bbd882f3a5a30c58db6ff/t-8WkR4h/test-project-8/dist/win-unpacked/Test App ßW.exe' --set-version-string FileDescription 'Test App ßW' --set-version-string ProductName 'Test App ßW' --set-version-string LegalCopyright 'Copyright © 2024 Foo Bar' --set-file-version 1.1.0.42 --set-product-version 1.1.0.42 --set-version-string InternalName 'Test App ßW' --set-version-string OriginalFilename '' --set-version-string CompanyName 'Foo Bar' --set-icon /tmp/et-db411cd21f3bbd882f3a5a30c58db6ff/t-8WkR4h/test-project-8/build/icon.ico
```

Is it possible for `app-builder` to provide an x64 compatible `rcedit.exe` to resolve this issue so that cross-platform builds can be managed from a single machine? It currently requires a minimum of two machines, or an older Mac which will begin reaching end of life shortly. The final Intel-based Apple machines will reach EOL by 2027 by my rough estimate, but many already have.

As such we don't want to buy older hardware for a self-hosted CI pipeline, but nor can we but newer hardware due to this incompatibility.

**Comment by Slapbox** [comment] 2024-02-08 23:18
Whoops, looks like a duplicate of #56.

**Closed by Slapbox** 2024-02-08 23:18 UTC
